<!--
DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

Copyright Â© 2008-2011 Oracle and/or its affiliates. All rights reserved.


The contents of this file are subject to the terms of either the GNU
General Public License Version 2 only ("GPL") or the Common
Development and Distribution License("CDDL") (collectively, the
"License"). You may not use this file except in compliance with the
License. You can obtain a copy of the License at
http://www.netbeans.org/cddl-gplv2.html
or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
specific language governing permissions and limitations under the
License.  When distributing the software, include this License Header
Notice in each file and include the License file at
nbbuild/licenses/CDDL-GPL-2-CP.  Sun designates this
particular file as subject to the "Classpath" exception as provided
by Sun in the GPL Version 2 section of the License file that
accompanied this code. If applicable, add the following below the
License Header, with the fields enclosed by brackets [] replaced by
your own identifying information:
"Portions Copyrighted [year] [name of copyright owner]"

Contributor(s):

The Original Software is NetBeans. The Initial Developer of the Original
Software is Sun Microsystems, Inc. Portions Copyright 2008 Sun
Microsystems, Inc. All Rights Reserved.

If you wish your version of this file to be governed by only the CDDL
or only the GPL Version 2, indicate your decision by adding
"[Contributor] elects to include this software in this distribution
under the [CDDL or GPL Version 2] license." If you do not indicate a
single choice of license, a recipient has the option to distribute
your version of this file under either the CDDL, the GPL Version 2 or
to extend the choice of license to its licensees as provided above.
However, if you add GPL Version 2 code and therefore, elected the GPL
Version 2 license, then the option applies only if the new code is
made subject to such option by the copyright holder.
-->
<testng-results>
  <reporter-output>
  </reporter-output>
  <suite name="Ant suite">
    <groups>
    </groups>
    <test name="Ant test">
      <class name="test.FailPassSkipTest">
        <test-method status="FAIL" signature="bTest()" name="bTest" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at test.FailPassSkipTest.bTest(FailPassSkipTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:580)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:478)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:617)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:885)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:110)
	at org.testng.TestRunner.runWorkers(TestRunner.java:712)
	at org.testng.TestRunner.privateRun(TestRunner.java:582)
	at org.testng.TestRunner.run(TestRunner.java:477)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:324)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:319)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:198)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:823)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:790)
	at org.testng.TestNG.run(TestNG.java:708)
	at org.testng.TestNG.privateMain(TestNG.java:860)
	at org.testng.TestNG.main(TestNG.java:833)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="SKIP" signature="cTest()" name="cTest" duration-ms="0" started-at="2008-11-21T21:43:50Z" depends-on-methods="test.FailPassSkipTest.aTest, test.FailPassSkipTest.bTest" finished-at="2008-11-21T21:43:50Z">
        </test-method>
        <test-method status="PASS" signature="aTest()" name="aTest" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
      </class>
      <class name="test.PassSkipTest">
        <test-method status="PASS" signature="setUp()" name="setUp" is-config="true" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
        <test-method status="PASS" signature="cleanUp()" name="cleanUp" is-config="true" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
        <test-method status="PASS" signature="aTest()" name="aTest" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
        <test-method status="SKIP" signature="bTest()" name="bTest" duration-ms="0" depends-on-groups="xxx" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method test.PassSkipTest.bTest() depends on nonexistent group "xxx"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method test.PassSkipTest.bTest() depends on nonexistent group "xxx"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:964)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:110)
	at org.testng.TestRunner.runWorkers(TestRunner.java:712)
	at org.testng.TestRunner.privateRun(TestRunner.java:582)
	at org.testng.TestRunner.run(TestRunner.java:477)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:324)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:319)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:198)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:823)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:790)
	at org.testng.TestNG.run(TestNG.java:708)
	at org.testng.TestNG.privateMain(TestNG.java:860)
	at org.testng.TestNG.main(TestNG.java:833)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
      </class>
      <class name="test.CleanUpTest">
        <test-method status="FAIL" signature="cleanUp()" name="cleanUp" is-config="true" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[some message]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: some message
	at test.CleanUpTest.cleanUp(CleanUpTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:580)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:398)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:145)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:82)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:210)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:113)
	at org.testng.TestRunner.runWorkers(TestRunner.java:712)
	at org.testng.TestRunner.privateRun(TestRunner.java:582)
	at org.testng.TestRunner.run(TestRunner.java:477)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:324)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:319)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:198)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:823)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:790)
	at org.testng.TestNG.run(TestNG.java:708)
	at org.testng.TestNG.privateMain(TestNG.java:860)
	at org.testng.TestNG.main(TestNG.java:833)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="aTest()" name="aTest" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
        <test-method status="PASS" signature="setUp()" name="setUp" is-config="true" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
      </class>
      <class name="test.FailingTest">
        <test-method status="FAIL" signature="aTest()" name="aTest" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at test.FailingTest.aTest(FailingTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:580)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:478)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:617)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:885)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:110)
	at org.testng.TestRunner.runWorkers(TestRunner.java:712)
	at org.testng.TestRunner.privateRun(TestRunner.java:582)
	at org.testng.TestRunner.run(TestRunner.java:477)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:324)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:319)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:198)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:823)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:790)
	at org.testng.TestNG.run(TestNG.java:708)
	at org.testng.TestNG.privateMain(TestNG.java:860)
	at org.testng.TestNG.main(TestNG.java:833)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="FAIL" signature="bTest()" name="bTest" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Expected an exception in test method test.FailingTest.bTest()]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException:
Expected an exception in test method test.FailingTest.bTest()
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1122)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:898)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:110)
	at org.testng.TestRunner.runWorkers(TestRunner.java:712)
	at org.testng.TestRunner.privateRun(TestRunner.java:582)
	at org.testng.TestRunner.run(TestRunner.java:477)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:324)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:319)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:198)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:823)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:790)
	at org.testng.TestNG.run(TestNG.java:708)
	at org.testng.TestNG.privateMain(TestNG.java:860)
	at org.testng.TestNG.main(TestNG.java:833)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="setUp()" name="setUp" is-config="true" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
        <test-method status="PASS" signature="cleanUp()" name="cleanUp" is-config="true" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
        <test-method status="PASS" signature="cTest()" name="cTest" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[catch this]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: catch this
	at test.FailingTest.cTest(FailingTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:580)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:478)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:617)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:885)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:110)
	at org.testng.TestRunner.runWorkers(TestRunner.java:712)
	at org.testng.TestRunner.privateRun(TestRunner.java:582)
	at org.testng.TestRunner.run(TestRunner.java:477)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:324)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:319)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:198)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:823)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:790)
	at org.testng.TestNG.run(TestNG.java:708)
	at org.testng.TestNG.privateMain(TestNG.java:860)
	at org.testng.TestNG.main(TestNG.java:833)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
      </class>
      <class name="test.NewTestNGTest">
        <test-method status="PASS" signature="cleanUp()" name="cleanUp" is-config="true" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
        <test-method status="PASS" signature="setUp()" name="setUp" is-config="true" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
        <test-method status="PASS" signature="aTest()" name="aTest" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
      </class>
      <class name="test.SetUpTest">
        <test-method status="FAIL" signature="setUp()" name="setUp" is-config="true" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at test.SetUpTest.setUp(SetUpTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:580)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:398)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:145)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:82)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:167)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.runWorkers(TestRunner.java:712)
	at org.testng.TestRunner.privateRun(TestRunner.java:582)
	at org.testng.TestRunner.run(TestRunner.java:477)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:324)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:319)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:198)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:823)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:790)
	at org.testng.TestNG.run(TestNG.java:708)
	at org.testng.TestNG.privateMain(TestNG.java:860)
	at org.testng.TestNG.main(TestNG.java:833)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="SKIP" signature="aTest()" name="aTest" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
        <test-method status="SKIP" signature="cleanUp()" name="cleanUp" is-config="true" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
      </class>
    </test>
    <test>
      <class name="test.SkippedExceptionTest">
        <test-method status="SKIP" signature="fexTest()" name="fexTest" duration-ms="0" started-at="2008-11-21T17:59:38Z" finished-at="2008-11-21T17:59:38Z">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
